spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#File size config
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true

#jwt
jwt:
  secret: JHS*2kl-$$7opk
  expiration: 6000000
  header: Authorization


